### ISSUE TITLE
Instro crashing Rack 1.1.6 on add

### ISSUE THREAD

**Issue by fractalgee** [Miserlou/RJModules#67]
New build finally cam down, however, Instro is crashing Rack reliably on add with following trace in log file (those win stacks are mighty mangled in the log...):

```
[367.268 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
36: ZN4rack10appDestroyEv 0x456435
35: raise 0xbfa6ac60
34: abort 0xbfa6f270
33: ZN9__gnu_cxx27__verbose_terminate_handlerEv 0x6fc5f170
32: ZN10__cxxabiv111__terminateEPFvvE 0x6fc581b0
31: ZSt9terminatev 0x6fd302b0
30: _cxa_throw 0x6fd39080
29: ZNK3stk3Stk11handleErrorENS_8StkError4TypeE 0xc59d702
28: ZN3stk8FileRead4openENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbjmd 0xc5f9f4a
27: ZN3stk8FileLoopC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbbmmb 0xc583fa4
26: ZN3stk6RhodeyC1Ev 0xc58ec56
25: ZN6InstroC1Ev 0xc65e8e0
24: ZZN4rack11createModelI6Instro12InstroWidgetEEPNS_6plugin5ModelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModel18createModuleWidgetEv 0xc698fc0
23: ZN4rack3app11AudioWidget12setAudioPortEPNS_5audio4PortE 0x49839c
22: ZN4rack3app8ModelBox8onButtonERKNS_5event6ButtonE 0x75cbc0
21: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
20: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
19: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
18: ZN4rack2ui12ScrollWidget8onButtonERKNS_5event6ButtonE 0x4a3ed4
17: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x771cd0
16: ZN4rack3app14BrowserOverlay8onButtonERKNS_5event6ButtonE 0x7530d0
15: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x771cd0
14: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
13: ZN4rack7updater17isUpdateAvailableEv 0x45914e
12: glfwPlatformUnlockMutex 0x4d78ae
11: CallWindowProcW 0xbefc57b0
10: CallWindowProcW 0xbefc57b0
9: glPushClientAttrib 0xa1293770
8: CallWindowProcW 0xbefc57b0
7: DispatchMessageW 0xbefc5370
6: glfwPlatformPollEvents 0x4daf66
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x781840
3: main 0x781840
2: main 0x781840
1: BaseThreadInitThunk 0xbf2c7bc0
0: RtlUserThreadStart 0xbfc2ceb0
```

**Comment by bitfetcher** [comment]
Seeing same. Here is the log from my Mac.


```
[0.000 info src/main.cpp:119] VCV Rack v1.1.6
[0.000 info src/main.cpp:120] Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
.
.
.
[7.009 fatal src/main.cpp:45] Fatal signal 6. Stack trace:
37: 1   Rack                                0x000000010bdfb3cd _ZL18fatalSignalHandleri + 45
36: 2   libsystem_platform.dylib            0x00007fff7ad72b5d _sigtramp + 29
35: 3   libc++abi.dylib                     0x00007fff77e159c5 GCC_except_table51 + 261
34: 4   libsystem_c.dylib                   0x00007fff7ac2c6a6 abort + 127
33: 5   libc++abi.dylib                     0x00007fff77e08641 __cxa_bad_cast + 0
32: 6   libc++abi.dylib                     0x00007fff77e087df _ZL26default_unexpected_handlerv + 0
31: 7   libobjc.A.dylib                     0x00007fff793bbeeb _ZL15_objc_terminatev + 105
30: 8   libc++abi.dylib                     0x00007fff77e1419e _ZSt11__terminatePFvvE + 8
29: 9   libc++abi.dylib                     0x00007fff77e13f86 __cxa_get_exception_ptr + 0
28: 10  libc++abi.dylib                     0x00007fff77e06f99 __cxa_get_globals + 0
27: 11  plugin.dylib                        0x00000000118538be _ZN3stk3Stk11handleErrorENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_8StkError4TypeE + 462
26: 12  plugin.dylib                        0x000000001185367a _ZNK3stk3Stk11handleErrorENS_8StkError4TypeE + 42
25: 13  plugin.dylib                        0x00000000118c730c _ZN3stk8FileRead4openENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbjmd + 396
24: 14  plugin.dylib                        0x0000000011837211 _ZN3stk8FileLoop8openFileENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbb + 97
23: 15  plugin.dylib                        0x0000000011837016 _ZN3stk8FileLoopC2ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbmmb + 118
22: 16  plugin.dylib                        0x0000000011840f36 _ZN3stk6RhodeyC2Ev + 358
21: 17  plugin.dylib                        0x000000001189d2b5 _ZN6InstroC2Ev + 149
20: 18  plugin.dylib                        0x000000001189d182 _ZZN4rack11createModelI6Instro12InstroWidgetEEPNS_6plugin5ModelERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEEN6TModel18createModuleWidgetEv + 34
19: 19  Rack                                0x000000010be25450 _ZN4rack3appL11chooseModelEPNS_6plugin5ModelE + 16
18: 20  Rack                                0x000000010be24f28 _ZN4rack3app8ModelBox8onButtonERKNS_5event6ButtonE + 56
17: 21  Rack                                0x000000010be19e58 _ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE + 200
16: 22  Rack                                0x000000010be19e58 _ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE + 200
15: 23  Rack                                0x000000010be19e58 _ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE + 200
14: 24  Rack                                0x000000010be5b4c8 _ZN4rack2ui12ScrollWidget8onButtonERKNS_5event6ButtonE + 200
13: 25  Rack                                0x000000010be15d28 _ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE + 200
12: 26  Rack                                0x000000010be15d28 _ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE + 200
11: 27  Rack                                0x000000010be23d92 _ZN4rack3app14BrowserOverlay8onButtonERKNS_5event6ButtonE + 18
10: 28  Rack                                0x000000010be15d28 _ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE + 200
9: 29  Rack                                0x000000010bdf5868 _ZN4rack5event5State12handleButtonENS_4math3VecEiii + 72
8: 30  AppKit                              0x00007fff4c437937 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5724
7: 31  AppKit                              0x00007fff4c36e1a6 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2295
6: 32  AppKit                              0x00007fff4c36d667 -[NSWindow(NSEventRouting) sendEvent:] + 478
5: 33  AppKit                              0x00007fff4c20ce4b -[NSApplication(NSEvent) sendEvent:] + 331
4: 34  Rack                                0x000000010bed3aad _glfwPlatformPollEvents + 109
3: 35  Rack                                0x000000010be12e0b _ZN4rack6Window3runEv + 139
2: 36  Rack                                0x000000010bdfaefa main + 1434
1: 37  Rack                                0x000000010bd94034 start + 52
0: 38  ???                                 0x0000000000000001 0x0 + 1
```

**Comment by Miserlou** [comment]
Damn, thanks for reporting. I'm guessing it has to do with this line:

https://github.com/Miserlou/RJModules/blob/master/src/Stk.h#L572

which needs to be replaced with `assetPlugin`

**Comment by Miserlou** [comment]
Actually, is this happening for `EssEff` as well? Could be related to the LCD display..

**Comment by bitfetcher** [comment]
Yes! It also crashes for me.

**Comment by Miserlou** [comment]
Probably related as well: https://github.com/Miserlou/RJModules/issues/62

All of the ones with the "LCD" displays crash on other people's systems, but not my own. Very annoying to debug, since I can't reproduce it myself! 

Sorry to waste everybody's time with crashing modules.

**Comment by bitfetcher** [comment]
FWIW, for me, the others (CHORD, PLAYABLECHORD, PINGPONG, RANGE, EUCLIDIAN) aren't causing a crash.

**Comment by fractalgee** [comment]
no worries, things happen @Miserlou , hope you can find this iffy. Never nice if you can't, but everyone else can repro it....  If you post a debug build maybe some better info could be found for you?

**Comment by david-c14** [comment]
I don't currently have any windows capability to debug this. But since people are drawing a link to the LCD display: I think you should seriously reconsider the way that you share a std::string between the module and the display.  It would be a lot safer to share an integer (possibly with an enum) and for the display to decide which string to display.

**Comment by Miserlou** [comment]
Okay, I have pushed a fix (I hope) to the `Euclidian` module, but since I can't reproduce the original crash on my own system, I'll need somebody else to confirm it's a working fix before I can port it to the other modules using LCD displays and push the fix to the store.

Anybody up for it? Thanks!

**Comment by faustoserone** [comment]
> Okay, I have pushed a fix (I hope) to the `Euclidian` module, but since I can't reproduce the original crash on my own system, I'll need somebody else to confirm it's a working fix before I can port it to the other modules using LCD displays and push the fix to the store.
> 
> Anybody up for it? Thanks!

I have compiled version 1.7.1. If the problem was the crash of the Euclidean module, in Windows 10 it is not solved. Sorry.

**Comment by Miserlou** [comment]
Dammit! Okay! Thank you for trying that, back to the drawing board. Can you paste the crash log from that?

**Comment by faustoserone** [comment]
1. 
[log.txt](https://github.com/Miserlou/RJModules/files/4105065/log.txt)

**Comment by NoxyNixie** [comment]
I've noticed in my terminal that the following error appears just before the crash which may more clearly indicate what is happening:

```
FileRead::open: could not open or find file (./plugins/RJModules/rawwaves/sinewave.raw)!

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'stk::StkError'
make: *** [Makefile:61: runr] Error 3
```

The path it lists is incorrect since plugins should be in the `plugins-v1` folder not `plugins` on top of that the path is a relative path which has me concerned since if this is relative to the executable working directory it will be incorrect.

**Comment by SteveRussell33** [comment]
https://github.com/Miserlou/RJModules/blob/master/src/Stk.h#L572

I changed the path to ``./plugins-v1/RJModules/rawwaves/`` as highlighted in the above post. This prevents a crash adding the module on Win 10.

**Comment by faustoserone** [comment]
> I changed the path to `./plugins-v1/RJModules/rawwaves/` as highlighted in the above post. This prevents a crash adding the module on Win 10.

Unfortunately, not for me. I had tried it a few days ago. Does not work. (BTW: I noticed that in the instro preview I don't see the musical instruments window. I don't know if it's a clue).

The log report:
[5.844 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
37: ZN4rack10appDestroyEv 0x456435
36: raise 0xf8e4ac60
35: abort 0xf8e4f270
34: ZN9__gnu_cxx27__verbose_terminate_handlerEv 0x6fc5f170
33: ZN10__cxxabiv111__terminateEPFvvE 0x6fc581b0
32: ZSt9terminatev 0x6fd302b0
31: _cxa_throw 0x6fd39080
30: ZN3stk3Stk11handleErrorENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_8StkError4TypeE 0x12f9b3a8
29: ZNK3stk3Stk11handleErrorENS_8StkError4TypeE 0x12f9b7b4
28: ZN3stk8FileRead4openENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbjmd 0x12f44542
27: ZN3stk8FileLoopC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbbmmb 0x12f41bfa
26: ZN3stk6RhodeyC2Ev 0x12f83700
25: ZN6InstroC1Ev 0x1300b450
24: ZZN4rack11createModelI6Instro12InstroWidgetEEPNS_6plugin5ModelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModel18createModuleWidgetEv 0x1303ee30
23: ZN4rack3app11AudioWidget12setAudioPortEPNS_5audio4PortE 0x49839c
22: ZN4rack3app8ModelBox8onButtonERKNS_5event6ButtonE 0x75cbc0
21: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
20: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
19: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
18: ZN4rack2ui12ScrollWidget8onButtonERKNS_5event6ButtonE 0x4a3ed4
17: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x771cd0
16: ZN4rack3app14BrowserOverlay8onButtonERKNS_5event6ButtonE 0x7530d0
15: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x771cd0
14: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
13: ZN4rack7updater17isUpdateAvailableEv 0x45914e
12: glfwPlatformUnlockMutex 0x4d78ae
11: CallWindowProcW 0xf8b657b0
10: CallWindowProcW 0xf8b657b0
9: glPushClientAttrib 0xd5643770
8: CallWindowProcW 0xf8b657b0
7: DispatchMessageW 0xf8b65370
6: glfwPlatformPollEvents 0x4daf66
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x781840
3: main 0x781840
2: main 0x781840
1: BaseThreadInitThunk 0xf83c7bc0
0: RtlUserThreadStart 0xf9a2ceb0

**Comment by SteveRussell33** [comment]
@faustoserone Where is your `plugins-v1` folder relative to the rack executable?

**Comment by faustoserone** [comment]
> @faustoserone Where is your `plugins-v1` folder relative to the rack executable?

c:\Users\Fausto\Documents\Rack\plugins-v1\

**Comment by SteveRussell33** [comment]
@faustoserone Ah I see. My plugins folder is in the Rack folder.

This line needs to changed to a constant I think that points to `rack::asset::pluginsPath + "RJModules/rawwaves/"`

**Comment by faustoserone** [comment]
> This line needs to changed to a constant I think that points to `rack::asset::pluginsPath + "RJModules/rawwaves/"`

Another workaround is to copy RJModules in "pluigns" directory under VCV\Rack, but I believe it should work in any plugins directory. Thank you, anyway, for your help :-)

**Comment by Miserlou** [comment]
Closed by #71! David rules!
